// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_FNGhAIOJZIMn4P6wZcrKT2ShDOvboHQ',
    appId: '1:910341489678:web:94d70ffa6270ab54c1285f',
    messagingSenderId: '910341489678',
    projectId: 'fir-flutter-codelens',
    authDomain: 'fir-flutter-codelens.firebaseapp.com',
    databaseURL: 'https://fir-flutter-codelens-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-codelens.firebasestorage.app',
    measurementId: 'G-7LVTSP8RDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi39Ye9DtoKzqkpYV1CmFjtE8ZpMCy0HE',
    appId: '1:910341489678:android:3cb207692d34d484c1285f',
    messagingSenderId: '910341489678',
    projectId: 'fir-flutter-codelens',
    databaseURL: 'https://fir-flutter-codelens-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-codelens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXvmCtvcbz0-Mx2EV3AEC9snwSk2yybOk',
    appId: '1:910341489678:ios:97b38b121a5e522fc1285f',
    messagingSenderId: '910341489678',
    projectId: 'fir-flutter-codelens',
    databaseURL: 'https://fir-flutter-codelens-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-codelens.firebasestorage.app',
    iosBundleId: 'com.example.codelensV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXvmCtvcbz0-Mx2EV3AEC9snwSk2yybOk',
    appId: '1:910341489678:ios:97b38b121a5e522fc1285f',
    messagingSenderId: '910341489678',
    projectId: 'fir-flutter-codelens',
    databaseURL: 'https://fir-flutter-codelens-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-codelens.firebasestorage.app',
    iosBundleId: 'com.example.codelensV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_FNGhAIOJZIMn4P6wZcrKT2ShDOvboHQ',
    appId: '1:910341489678:web:819febd2681b45c0c1285f',
    messagingSenderId: '910341489678',
    projectId: 'fir-flutter-codelens',
    authDomain: 'fir-flutter-codelens.firebaseapp.com',
    databaseURL: 'https://fir-flutter-codelens-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-codelens.firebasestorage.app',
    measurementId: 'G-2W66SZJZWZ',
  );
}
